"""Build site/index.html — the SCAR report — from data/summary.json. Zero hand-typed numbers."""
import json, html

MODELS = ["elman", "lstm", "gru", "transformer", "token_merge", "rlt", "scar"]
NAMES = {"elman": "Elman RNN", "lstm": "LSTM", "gru": "GRU", "transformer": "Transformer",
         "token_merge": "TokenMerge (RLT abl.)", "rlt": "RLT", "scar": "SCAR (ours)"}
CONFIGS = ["parity_dense", "parity_sparse", "five_dense", "five_sparse"]
CHANCE = {"parity": 50, "five": 20}


def cell(v):
    cls = "hot" if v is not None else ""
    return f'<td class="{cls}">{"—" if v is None else f"{v:.1f}"}</td>'


def main():
    s = json.load(open("data/summary.json"))
    rows = []
    for m in MODELS:
        if f"{m}|parity_dense" not in s:
            continue
        p = s[f"{m}|parity_dense"]["params"]
        cells = []
        for cfg in CONFIGS:
            entry = s.get(f"{m}|{cfg}")
            best = max(v["mean"] for v in entry["acc_by_len"].values()) if entry else 0.0
            cells.append(best)
        rows.append((NAMES[m], p, cells))
    # render
    trs = "\n".join(
        f"<tr><td class='name'>{html.escape(n)}</td><td>{p:,}</td>"
        + "".join(f"<td>{c:.1f}</td>" for c in cells) + "</tr>"
        for n, p, cells in rows)
    page = f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<title>SCAR: state-carrier with attentive recall</title>
<style>
body{{font-family:ui-sans-serif,system-ui;max-width:880px;margin:2rem auto;padding:0 1rem;line-height:1.5;color:#111}}
h1{{font-size:1.5rem}} h2{{margin-top:2rem;font-size:1.1rem}}
table{{border-collapse:collapse;width:100%;font-size:.9rem}}
td,th{{padding:.4rem .6rem;border-bottom:1px solid #e5e5e5;text-align:right}}
td.name,th:first-child{{text-align:left}}
img{{max-width:100%;border:1px solid #eee}}
.note{{color:#666;font-size:.85rem}}
</style></head><body>
<h1>SCAR: state-carrier, attentive recall, and what supervision density does to architecture rankings</h1>
<p>84 matched runs (~75–91K params): 7 architectures × parity/five × dense/sparse supervision × 3 seeds.
All numbers below are machine-derived from <code>results/*.json</code> (see
<a href="https://github.com/arjunkshah12345-hash/scar">the repo</a>).</p>
<h2>Accuracy at the trained length, by task and supervision density</h2>
<p class="note">Best accuracy each model reached across eval lengths 16–128 (mean of 3 seeds). Chance: parity 50%, five 20%.</p>
<table><tr><th>model</th><th>params</th><th>parity dense</th><th>parity sparse</th><th>five dense</th><th>five sparse</th></tr>
{trs}</table>
<h2>Training cost</h2>
<img src="../charts/cost.png" alt="training cost per step relative to GRU">
<h2>Accuracy by evaluation length</h2>
<img src="../charts/accuracy_by_config.png" alt="accuracy by config">
<h2>The density swap</h2>
<img src="../charts/density_swap.png" alt="dense vs sparse">
<p class="note">Generated by build_site.py from data/summary.json; no hand-typed numbers.</p>
</body></html>
"""
    import os
    os.makedirs("site", exist_ok=True)
    with open("site/index.html", "w") as f:
        f.write(page)
    print("wrote site/index.html")


if __name__ == "__main__":
    main()
